accounts/urls.py
from django.conf.urls import url
from django.urls import path

from accounts.views import Login, Logout

app_name = 'accounts'
urlpatterns = [
#    path('signup/', Signup.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),

    #   path('employee_list/', EmployeeList.as_view(), name='employee_list'),
    #url(r'employee_detail/(?P<employee_id>[0-9]+)/$', EmployeeDetail.as_view(), name='employee_detail'),
   # path('employee_add/', EmployeeAdd.as_view(), name='employee_add'),
    #path('employee_edit/', EmployeeEdit.as_view(), name='employee_edit'),
    #path('employee_remove/', EmployeeRemove.as_view(), name='employee_remove'),
    #path('api/', getApi.as_view(), name='api'),
]

contact/urls.py
from django.urls import path, include
from contact.views import contact, thanks

app_name = 'contact'
urlpatterns = [
    path('us/', contact, name='contact'),
    path('thanks/', thanks, name='thanks'),

]

customers/urls.py
from django.conf.urls import url
from django.urls import path

from customers.views import Signup, Login , EditProfile #, Logout

app_name = 'customers'
urlpatterns = [
    url('signup/', Signup.as_view(), name='signup'),
    url('login/', Login.as_view(), name='login'),
    url('edit profile/', EditProfile.as_view(), name='edit_profile'),

    #url('logout/', Logout.as_view(), name='logout'),

    # url('employee_list/', EmployeeList.as_view(), name='employee_list'),
    # url(r'employee_detail/(?P<employee_id>[0-9]+)/$', EmployeeDetail.as_view(), name='employee_detail'),
    # url('employee_add/', EmployeeAdd.as_view(), name='employee_add'),
    # url('employee_edit/', EmployeeEdit.as_view(), name='employee_edit'),
    # url('employee_remove/', EmployeeRemove.as_view(), name='employee_remove'),
    # url('api/', getApi.as_view(), name='api'),
]

hesaab/urls.py
from django.conf.urls import url
from django.urls import path

from accounts.views import *

app_name = 'hesab'
urlpatterns = [
]

test_exchange/urls.py
from django.contrib import admin
from django.urls import path, include

from test_exchange.views import About , Laws , HomePage
from transactions.views import TestExchange , CurencyNow , TransactionsCosts
#from accounts.views import HomePage2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
    path('customers/', include('customers.urls')),
    path('employee/', include('employee.urls')),
    path('hesaab/', include('hesaab.urls')),
    path('manager/', include('manager.urls')),
    #path('home/', HomePage2.as_view(), name='home_page2'),
    path('test exchange/', TestExchange.as_view(), name='test_exchanged'),
    path('curency now/', CurencyNow.as_view(), name='curency_now'),
    path('transactions cost/', TransactionsCosts.as_view(), name='transaction_cost'),
    path('', HomePage.as_view(), name='home_page'),



    path('about/', About.as_view(), name='about'),
    path('laws/', Laws.as_view(), name='laws'),
    path('contact/', include('contact.urls')),

]

transactions/urls.py
from django.contrib import admin
from django.urls import path, include

from transactions.views import TransactionsCosts


app_name = 'transactions'
urlpatterns = [
    #path('Addition/', Addition.as_view(), name='Addition'),
    path('just first/',TransactionsCosts.new_item , name='just_first'),
    #path('just first/', TransactionsCosts.new_item, name='just_first'),

]

templates/abouts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>درباره ی ما</title>
</head>
<body>
        <div>          <a href="{% url 'home_page'  %}">صفحه اصلی</a></div>

    <div> موسسه ی پرداخت ارزی امیر از سال 97 شروع به کار کرده و تا کنون با بیش از 5 روز قدمت به پشتوانه ی حمایت شما همراهان گرامی یکی از بهترین خدمات رسانان ارزی در کشور عزیزمان ایران می باشد </div>

</body>
</html>

templates/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>صفحه اصلی</title>
</head>
<body>
{% if user.is_authenticated %}
  <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
{% else %}
  <p>Welcome, new user. Please log in.</p>
{% endif %}

        <div>          <a href="{% url 'home_page'  %}">صفحه اصلی</a></div>

        <div>          <a href="{% url 'customers:signup'  %}">ثبت نام</a></div>

        <div>          <a href="{% url 'customers:edit_profile'  %}">تغییر اطلاعات شخصی</a></div>

        <div>          <a href="{% url 'transactions:just_first'  %}">فقط بار اول</a></div>


        <div>          <a href="{% url 'customers:login'  %}">ورود</a></div>

        <div>          <a href="{% url 'accounts:logout'  %}">خروج از حساب کاربری</a> </div>

        <div>          <a href="{% url 'curency_now'  %}">نرخ لحظه ای ارز</a> </div>

        <div>          <a href="{% url 'test_exchanged'  %}">انجام تبدیل آزمایشی</a> </div>

        <div>          <a href="{% url 'transaction_cost'  %}">نرخ کارمزد</a> </div>

        <div>          <a href="{% url 'about'  %}">درباره ی ما</a> </div>

        <div>          <a href="{% url 'laws'  %}">قوانین</a> </div>

        <div>          <a href="{% url 'contact:contact'  %}">ارتباط با ما</a> </div>


</body>
</html>

templates/laws.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>قوانین</title>
</head>
<body>
        <div>          <a href="{% url 'home_page'  %}">صفحه اصلی</a></div>
    <div> قوانین این سامانه بدین شرح است:  </div>
    <div>1- برای ورود حتما باید ثبت نام کنید. بدون این مورد تنها می توانید از خدمات عمومی ما استفاده نمایید  </div>
    <div> 2- این سامانه مسئولیتی در زمینه ی احراز هویت افراد ندارد. صرفا سامانه ای برای خدمت رسانی و تسهیل امور می باشد.   </div>
    <div>  3- لطفا درب پارکینگ پارک نفرمایید</div>
    <div>4- هیچوقت یک ایراتی را تهدید نکنید </div>

</body>
</html>